env:
  global:
    - CC_TEST_REPORTER_ID=e01a054df0ecd63b335e94bd3cce16e783ee6f794ee5cddced710004d0004075
  language: node_js
  node_js:
    - 7
    - 6
    - 4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
